# Generated by Django 5.0.7 on 2024-08-18 07:24

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=3000,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="В архиве"),
                ),
                (
                    "release_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Тип релиза",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1/4"), (2, "2/4"), (3, "3/4"), (4, "4/4")],
                        default=1,
                        verbose_name="Приоритет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компонент",
                "verbose_name_plural": "Компоненты",
                "ordering": ("-start_date",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgressStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#D6E4FF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Цвет тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус работы",
                "verbose_name_plural": "Статусы работы",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=3000,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="В архиве"),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("-start_date",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=3000,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="В архиве"),
                ),
            ],
            options={
                "verbose_name": "Сервис",
                "verbose_name_plural": "Сервисы",
                "ordering": ("-start_date",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#D6E4FF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Цвет тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
    ]
