volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: tatianabelova/gazprom_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/Employee/
  
  nginx:
    image: tatianabelova/gazprom_gateway
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - static:/staticfiles/
      - media:/media/Employee/