# Generated by Django 5.0.7 on 2024-08-18 07:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company_structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="director",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="company",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец продукта",
            ),
        ),
        migrations.AddField(
            model_name="companydepartment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="company_structure.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="companydepartment",
            name="head",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="department",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель департмента",
            ),
        ),
        migrations.AddField(
            model_name="companyoffice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offices",
                to="company_structure.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="companyteam",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="company_structure.companydepartment",
                verbose_name="Департамент",
            ),
        ),
        migrations.AddField(
            model_name="companyteam",
            name="team_lead",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель отдела",
            ),
        ),
        migrations.AddField(
            model_name="companyunit",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="company_structure.companyteam",
                verbose_name="Отдел",
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="position_unique_name",
                violation_error_message="Данное название уже существует.",
            ),
        ),
        migrations.AddConstraint(
            model_name="companydepartment",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="companydepartment_unique_name",
                violation_error_message="Данное название уже существует.",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyteam",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="companyteam_unique_name",
                violation_error_message="Данное название уже существует.",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyunit",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="companyunit_unique_name",
                violation_error_message="Данное название уже существует.",
            ),
        ),
    ]
