from api.views.employee import EmployeeViewSet  # noqa
from api.views.employee_status import EmployeeStatusReadOnlyViewset  # noqa
from api.views.skill import SkillReadOnlyViewSet  # noqa
from api.views.progress_status import ProgressStatusReadOnlyViewset  # noqa
from api.views.tag import TagReadOnlyViewSet  # noqa
from api.views.timezone import TimeZoneReadOnlyViewSet  # noqa
from api.views.position import PositionReadOnlyViewSet  # noqa
from api.views.office import OfficeReadOnlyViewset  # noqa
from api.views.company_structure import CompanyStructureViewset  # noqa
